jobs:
  create-github-release:
    environment: Release
    name: Create GitHub Release and Git tag
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: cucumber/action-create-github-release@v1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
name: Release GitHub
on:
  repository_dispatch:
    types: trigger-ga___release-github.yml
