jobs:
  publish-mvn:
    environment: Release
    name: Publish Maven Package
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      uses: cucumber/action-publish-mvn@v2.0.0
      with:
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        nexus-password: ${{ secrets.SONATYPE_PASSWORD }}
        nexus-username: ${{ secrets.SONATYPE_USERNAME }}
name: Release Maven
on:
  repository_dispatch:
    types: trigger-ga___release-java.yml
