jobs:
  build:
    name: Build Java ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.version }}
    - continue-on-error: true
      name: Install dependencies
      run: ./mvnw install -Pinclude-extra-modules -DskipTests=true -DskipITs=true
        -D"archetype.test.skip=true" -D"maven.javadoc.skip=true" --batch-mode -D"style.color=always"
        --show-version
    - continue-on-error: true
      env:
        CUCUMBER_PUBLISH_TOKEN: ${{ secrets.CUCUMBER_PUBLISH_TOKEN }}
      name: Test
      run: ./mvnw verify -Pinclude-extra-modules -D"style.color=always"
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        version:
        - 17
        - 21
  javadoc:
    name: Javadoc
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Install dependencies
      run: ./mvnw install -DskipTests=true -DskipITs=true -Darchetype.test.skip=true
        -Dmaven.javadoc.skip=true --batch-mode -Dstyle.color=always --show-version
    - continue-on-error: true
      name: Javadoc
      run: ./mvnw javadoc:jar -Dstyle.color=always
  semver:
    name: Semver
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Install dependencies
      run: ./mvnw install -DskipTests=true -DskipITs=true -Darchetype.test.skip=true
        -Dmaven.javadoc.skip=true --batch-mode -Dstyle.color=always --show-version
    - continue-on-error: true
      name: Test (Semver check)
      run: ./mvnw verify -Pcheck-semantic-version -DskipTests=true -DskipITs=true
        -Darchetype.test.skip=true -Dstyle.color=always
name: Test Java
on:
  repository_dispatch:
    types: trigger-ga___test-java.yml
